spring:
  datasource:
    url: jdbc:mysql://localhost:33061/staffjoy_account?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    show-sql: true
server:
  port: 8081